#!/usr/bin/env python3
"""Convert the TreeScanPL10k HELIOS ALS release to the DualCrown3D format.

The supplied full TLS-derived crown polygons are copied without modification.
Only point clouds are voxelised; complete held-out train/val/test assignments are
preserved exactly as generated by the HELIOS dataset pipeline.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import geopandas as gpd
import laspy
import numpy as np
import rasterio
from rasterio.transform import from_origin


PROJECT = Path(__file__).resolve().parents[1]
WORKSPACE = PROJECT.parent


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024**2), b""):
            digest.update(block)
    return digest.hexdigest()


def write_csv(path: Path, rows: list[dict]) -> None:
    fields = list(dict.fromkeys(key for row in rows for key in row))
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def voxelise(
    xyz: np.ndarray, intensity: np.ndarray, tree_id: np.ndarray, voxel_size: float
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    origin = np.floor(xyz.min(0) / voxel_size) * voxel_size
    grid = np.floor((xyz - origin) / voxel_size).astype(np.int32)
    shifted = grid.astype(np.int64) - grid.min(0).astype(np.int64)
    extent = shifted.max(0) + 1
    key = shifted[:, 0] + extent[0] * (shifted[:, 1] + extent[1] * shifted[:, 2])
    # Prefer labelled vegetation when multiple returns occupy the same voxel.
    order = np.lexsort((-(tree_id > 0).astype(np.int8), key))
    _, first = np.unique(key[order], return_index=True)
    selected = np.sort(order[first])
    return xyz[selected], intensity[selected], tree_id[selected], origin


def make_chm(path: Path, xyz: np.ndarray, resolution: float = 0.5) -> None:
    left, bottom = np.floor(xyz[:, :2].min(0) / resolution) * resolution
    right, top = np.ceil(xyz[:, :2].max(0) / resolution) * resolution
    width = max(1, int(round((right - left) / resolution)))
    height = max(1, int(round((top - bottom) / resolution)))
    cc = np.clip(np.floor((xyz[:, 0] - left) / resolution).astype(np.int64), 0, width - 1)
    rr = np.clip(np.floor((top - xyz[:, 1]) / resolution).astype(np.int64), 0, height - 1)
    values = np.full(height * width, -9999.0, dtype=np.float32)
    np.maximum.at(values, rr * width + cc, np.maximum(xyz[:, 2], 0))
    with rasterio.open(
        path, "w", driver="GTiff", width=width, height=height, count=1,
        dtype="float32", transform=from_origin(left, top, resolution, resolution),
        nodata=-9999, compress="deflate",
    ) as dst:
        dst.write(values.reshape(height, width), 1)
        dst.update_tags(height_normalization="provided_helios_height_agl", uses_tree_id="false")


def convert_plot(source: Path, target: Path, split: str, voxel_size: float,
                 allow_unobserved_training_crowns: bool = False) -> dict:
    laz_path = next(source.glob("*_ALS.laz"))
    crowns_path = source / "crowns_full.gpkg"
    cloud = laspy.read(laz_path)
    required = {"treeID", "height_agl", "completelyInside"}
    available = set(cloud.point_format.dimension_names)
    if missing := required - available:
        raise ValueError(f"{laz_path}: missing dimensions {sorted(missing)}")
    xyz = np.column_stack((cloud.x, cloud.y, np.asarray(cloud.height_agl))).astype(np.float64)
    intensity = np.asarray(cloud.intensity, dtype=np.float32)
    tree_id = np.asarray(cloud.treeID, dtype=np.int64)
    complete = np.asarray(cloud.completelyInside) > 0
    tree_id[(tree_id > 0) & ~complete] = -1
    finite = np.isfinite(xyz).all(1) & np.isfinite(intensity)
    xyz, intensity, tree_id = xyz[finite], intensity[finite], tree_id[finite]
    raw_points = len(xyz)
    xyz, intensity, tree_id, voxel_origin = voxelise(xyz, intensity, tree_id, voxel_size)
    lo, hi = np.percentile(intensity, (1, 99))
    intensity = np.clip((intensity - lo) / max(float(hi - lo), 1.0), 0, 1).astype(np.float32)

    xy_origin = np.floor(xyz[:, :2].min(0) * 2) / 2
    source_origin = np.asarray([xy_origin[0], xy_origin[1], 0.0], dtype=np.float64)
    coord = (xyz - source_origin).astype(np.float32)
    grid = np.floor((xyz - voxel_origin) / voxel_size).astype(np.int32)
    offsets = np.zeros_like(coord)
    positive = tree_id > 0
    if positive.any():
        unique, inverse, counts = np.unique(tree_id[positive], return_inverse=True, return_counts=True)
        sums = np.zeros((len(unique), 3), dtype=np.float64)
        np.add.at(sums, inverse, coord[positive])
        offsets[positive] = sums[inverse] / counts[inverse, None] - coord[positive]

    crowns = gpd.read_file(crowns_path)
    crown_ids = set(crowns["tree_id"].astype(int))
    point_ids = set(tree_id[tree_id > 0].astype(int))
    if point_ids - crown_ids or (crown_ids != point_ids and not (
            split == 'train' and allow_unobserved_training_crowns)):
        raise ValueError(
            f"{source.name}: full-crown/ALS ID mismatch: "
            f"missing points={sorted(crown_ids-point_ids)}, missing crowns={sorted(point_ids-crown_ids)}"
        )

    target.mkdir(parents=True, exist_ok=True)
    npz_path = target / "points_0p25m.npz"
    np.savez_compressed(
        npz_path, coord=coord, grid_coord=grid, intensity=intensity,
        tree_id=tree_id.astype(np.int32), instance_offset=offsets,
        source_origin=source_origin, voxel_origin=voxel_origin,
        voxel_size=np.float32(voxel_size), raw_points=np.int64(raw_points),
    )
    copied_laz = target / "points.laz"
    copied_crowns = target / "crowns_full.gpkg"
    shutil.copy2(laz_path, copied_laz)
    shutil.copy2(crowns_path, copied_crowns)
    chm_path = target / f"chm_{source.name}.tif"
    make_chm(chm_path, xyz)

    row = {
        "dataset_id": f"treescan_helios__{source.name}",
        "source_dataset": "TreeScanPL10k_HELIOS",
        "collection": "TREESCAN_PL10K",
        "official_split": split,
        "original_las": str(laz_path.resolve()),
        "annotation_method": "physics_simulation_exact_points_tls_full_crowns",
        "spatial_crs": "LOCAL_METRIC",
        "bounds": json.dumps([float(xyz[:, 0].min()), float(xyz[:, 1].min()),
                              float(xyz[:, 0].max()), float(xyz[:, 1].max())]),
        "crs_wkt": "",
        "source_sha256": sha256(laz_path),
        "group_id": hashlib.sha256(source.name.encode()).hexdigest()[:16],
        "model_split": split,
        "source_las": str(copied_laz.resolve()),
        "output": str(npz_path.resolve()),
        "gt_vector": str(copied_crowns.resolve()),
        "chm": str(chm_path.resolve()),
        "raw_points": raw_points,
        "voxels": len(coord),
        "instances": len(crowns),
        "tree_voxels": int(positive.sum()),
        "voxel_size": voxel_size,
        "height_normalization": "provided_helios_height_agl",
        "gt_method": "complete_tls_crown_polygon_unmodified",
        "copy_verified": True,
        "grid_version": 2,
        "repaired_grid_collisions": 0,
        "supervision_changed": False,
        "npz_sha256": sha256(npz_path),
        "unobserved_full_crowns": len(crown_ids - point_ids),
    }
    (target / "metadata.json").write_text(json.dumps(row, indent=2) + "\n")
    return row


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=WORKSPACE / "TreeScanPL10k_HELIOS_ALS_v1")
    parser.add_argument("--output", type=Path, default=WORKSPACE / "dualcrown3d_treescan_helios_v1")
    parser.add_argument("--voxel-size", type=float, default=0.25)
    args = parser.parse_args()
    source, output = args.source.resolve(), args.output.resolve()
    if (output / "READY.json").exists():
        raise FileExistsError(f"Prepared dataset already complete: {output}")
    rows = []
    for split in ("train", "val", "test"):
        for plot in sorted((source / "prepared_dataset" / split).iterdir()):
            if plot.is_dir():
                rows.append(convert_plot(plot, output / split / plot.name, split, args.voxel_size))
                print(f"Prepared {split}: {plot.name}", flush=True)
    write_csv(output / "manifest.csv", rows)
    for split in ("train", "val", "test"):
        write_csv(output / f"manifest_{split}.csv", [row for row in rows if row["model_split"] == split])
    counts = Counter(row["model_split"] for row in rows)
    report = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "source": str(source), "plots": len(rows), "split_counts": dict(counts),
        "instances": sum(int(row["instances"]) for row in rows),
        "voxels": sum(int(row["voxels"]) for row in rows),
        "voxel_size": args.voxel_size,
        "full_crown_polygons_modified": False,
        "split_assignments_modified": False,
        "manifest_sha256": sha256(output / "manifest.csv"),
    }
    (output / "READY.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2), flush=True)


if __name__ == "__main__":
    main()
